### ISSUE TITLE
Change capitalization for saxon genitive

### ISSUE THREAD

**Issue by ElLorans** [ElLorans/Best-MTG-Deck#14]
.title() is widely used in the project, resulting in bad capitalization: "Chandra'S Defeat" in place of "Chandra's Defeat". Changing all .title() instances with something able to recognise saxon genitive would be nice.

**Comment by Badboy-16** [comment]
Hi I would like to work on this issue and will submit a PR in the coming days. :)

**Comment by ElLorans** [comment]
Solved by https://github.com/ElLorans/Best-MTG-Deck/pull/15

**Comment by ElLorans** [comment]
Thanks for the help! Changes have been pushed to deployment and are now live.

**Comment by Badboy-16** [comment]
> Thanks for the help! Changes have been pushed to deployment and are now live.

Cheers mate. Happy to contribute! :)
