### ISSUE TITLE
Add Penny Dreadful format

### ISSUE THREAD

**Issue by ghost** [ElLorans/Best-MTG-Deck#24]
I wanted to add the [Penny Dreadful format](https://pennydreadfulmagic.com/). I've forked the repository to work on it: https://codeberg.org/LifeSymbiont/Best-MTG-Deck

**Comment by HarleyQuinn-Z6** [comment]
Finished adding the Penny Dreadful format of my repository. [Here is the commit](https://codeberg.org/LifeSymbiont/Best-MTG-Deck/src/commit/870c06e041f6c766a353cf638f2e1ef20c67ad2f)

**Comment by ElLorans** [comment]
Would you open a pull request? What did you use to get the data? I use https://github.com/ElLorans/GoldfishScrape even though I haven't updated the db in a while.
