### ISSUE TITLE
Update data automatically

### ISSUE THREAD

**Issue by ghost** [ElLorans/Best-MTG-Deck#25]
I would like to automate the process of getting the data. Specially to have up-to-date prices.

It would be nice to know where did you download the decks, prices, data_types, rarity from. Right now I'm getting it from scryfall bulk data download, but I see some inconsistencies between that data and the one you used. For example the rarity is lower case instead of capitalized and the data_types include the sub-types while the one you provide doesn't. That makes me believe that isn't the data you used and I would have to process it so that it's the same. But I could also download it directly from the same place that you did.

Edit: never mind I've now seen the scraper is at [ElLorans/GoldfishScrape](https://github.com/ElLorans/GoldfishScrape). I wish I had seen that before scraping the penny dreadful decks from https://dreadrise.wizzerinus.tk/
Edit2: that scraper only gets the decklists, so I'm still curious about the rest of the data.

**Comment by ElLorans** [comment]
Sorry for taking 6 months to reply, I had received no notification. I have another private repo which I'll make public as soon as I can, but I use scryfall bulk data too.

**Comment by ElLorans** [comment]
Repo is now public: https://github.com/ElLorans/Best-MTG-Deck-GenerateData
