### ISSUE TITLE
When was the cube list last updated?

### ISSUE THREAD

**Issue by cbs38139** [ElLorans/Best-MTG-Deck#26]
Also, would it be possible to run the 100 most drafted cubes?

**Comment by cbs38139** [comment]
Or even better: I am running your code on my machine now (works like a charm, thank you btw). How do I update the cube list myself?

**Comment by ElLorans** [comment]
Sorry @cbs38139, I had missed this issue. The cube list was updated a long time ago, I can update it again. Any relevant source you prefer? CubeCobra? You can update it by modifying database.py. You can add a new dictionary inside the variable "Cube". The format is 

`Cube = {"<CubeName>": {"<CardName>": 1,  "<CardName>": 2, }, "<CubeName2>": {"<CardName>": 1, ...

**Comment by cbs38139** [comment]
CubeCobra would be fantastic!Am 04.10.2024 um 16:49 schrieb Lorenzo ***@***.***>:﻿
Sorry @cbs38139, I had missed this issue. The cube list was updated a long time ago, I can update it again. Any relevant source you prefer? CubeCobra? You can update it by modifying database.py. You can add a new dictionary inside the variable "Cube". The format is
`Cube = {"": {"": 1,  "": 2, }, "": {"": 1, ...

**Comment by cbs38139** [comment]
Oh! Could you also share the steps how you download cubes from cube cobra, please?Am 04.10.2024 um 16:49 schrieb Lorenzo ***@***.***>:﻿
Sorry @cbs38139, I had missed this issue. The cube list was updated a long time ago, I can update it again. Any relevant source you prefer? CubeCobra? You can update it by modifying database.py. You can add a new dictionary inside the variable "Cube". The format is
`Cube = {"": {"": 1,  "": 2, }, "": {"": 1, ...

**Comment by ElLorans** [comment]
I created my scraper. (https://github.com/ElLorans/GoldfishScrape). This is for cubecobra: https://github.com/ElLorans/GoldfishScrape/blob/master/MtgScraper/CubeCobraScraper.py

**Comment by cbs38139** [comment]
Ah! That makes it way easier. I will try to run it on my side. This is the search term I would put in:

https://cubecobra.com/search/twobert?order=pop&ascending=false

**Comment by ElLorans** [comment]
Then you should put that in line 26 and it should hopefully work. If you manage to download cubes list, you can then open a pull request and see that on https://bestdeckforyou.pythonanywhere.com/ too (but I would not put a 100 of those online).

**Comment by cbs38139** [comment]
Hi! I get JSON parsing error:

json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 11122 (char 11121)

Does it run on your side?

**Comment by ElLorans** [comment]
I edited the code so that you can now do as you wish: https://github.com/ElLorans/GoldfishScrape/blob/master/MtgScraper/CubeCobraScraper.py. Simply change the url at line 85

**Comment by ElLorans** [comment]
Updated cubes list in https://github.com/ElLorans/Best-MTG-Deck/commit/859ce1a8b2df2898a5a65f65f6aaab24b6bfe23b

**Comment by cbs38139** [comment]
OMG, it works like a charm, thank you!🙏 Am 19.10.2024 um 23:03 schrieb Lorenzo ***@***.***>:﻿
I edited the code so that you can now do as you wish: https://github.com/ElLorans/GoldfishScrape/blob/master/MtgScraper/CubeCobraScraper.py. Simply change the url at line 85
